### ISSUE TITLE
hover va active

### ISSUE THREAD

**Issue by SayramovAzizbek** [JumabaevZiyodilla/Bookmark#3]
![image](https://user-images.githubusercontent.com/96992119/176933484-17b289dd-e1a6-4939-a5e7-6e016493ab73.png)
Bu yerda ham color i qizil bo'lishi ham bottomi qizil bo'lishi sal hatoroq bo'lsa kerak, chunki hover effecti berilgan edi va unda faqatgina color o'zgarar edi sizda border-bottom ham qo'shilyapti, border bottom qo'shilishi hato emas lekn u asosan class bo'ladi va shu 3 tasidan bittasiga bosganizda qaysi biri bosilgan bo'lsa shuni border-bottom i ishlashi kerak, ya'ni rangi agar shuni to'g'irlab qo'ysangiz manimcha ancha yaxshi bo'lar edi

**Comment by JumabaevZiyodilla** [comment]
Done
